### PR TITLE
Useful API functions

### PR DESCRIPTION
**Pull request by okankocyigit**
I had need some functionality like getting `Country`  by `isoCode` and `callingCode`, when i  want to show country image or name that user has selected it before so I create  two functions. 

```
let viewController = CountryPickerViewController()
let germany = viewController.getCountry(callingCode: "+49")
let turkey = viewController.getCountry(isoCode: "TR")
```

Hope this is not just my need :)

### CODE REVIEW

**Comment by kmikael** [comment]
I think this is a very good idea. I feel like, ideally the finding methods would be in `Country`. SO something like `Country.find(isoCode: "TR")` and `Country.find(callingCode: "+90")`. This will allow you to use this info in model contexts without instantiating a view controller.

To do this, we could move the country creating, JSON parsing etc. from `CountryDataSource` to `Country`.

What do you think about that?

PS: I had an not pushed commit setting the  podspec platform to `9.0`. So this is a conflict now, sorry about that. You can remove that change.

**Comment by okankocyigit** [comment]
@kmikael 

I think that would be a better aproach. Creating an instance of viewcontroller for getting country is redundant.

**Comment by kmikael** [comment]
@okankocyigit Awesome, would you be interested in going forward with those changes? I can then merge them into master and make  new release.

**Comment by okankocyigit** [comment]
@kmikael, sure i will when I have time.

**Comment by okankocyigit** [comment]
@kmikael it seems to be ok for me. Could you please check if I did something wrong?. still a newbie 😄

**Comment by kmikael** [comment]
Thanks, @okankocyigit! 👍🏻 I changed the way the locale works a little to make it less global and added a few test.

**Pull request merged**
