### PR TITLE
Better Installation section

### PR DESCRIPTION
**Pull request by lfarah**

### CODE REVIEW

**Comment by kmikael** [comment]
I'm not sure about the "To get the full benefits import `Planet` wherever you import UIKit" part. There is usually only need to import Planet in one or two specific places.

It's a great idea to clarify the insulation though.

**Comment by lfarah** [comment]
I mean that you put the `import Planet` under `UIKit` on the class you need to use planet, and not on every single file.

What do you want me to change it to to make it more clear?

**Comment by kmikael** [comment]
Maybe that sentence should be in the `Example` section as it is referring to both CocoaPods and manual installation.

We could use something like:

First import the library:

``` swift
 import Planet
```

Then create the view controller: … etc.

**Comment by lfarah** [comment]
@kmikael what do you think?

**Comment by kmikael** [comment]
Looks good, thank you.

One last thing, can you change "Then, the View Controller:" to "Then, create the view controller:".

**Comment by kmikael** [comment]
Thank you! 👍🏻

**Pull request merged**
